-- Anthony Davis Game Logs Tables

-- 2020-2021 Season
create table game_logs_2020_2021 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2019-2020 Season
create table game_logs_2019_2020 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2021-2022 Season
create table game_logs_2021_2022 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2022-2023 Season
create table game_logs_2022_2023 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2023-2024 Season
create table game_logs_2023_2024 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2017-2018 Season
create table game_logs_2017_2018 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2018-2019 Season
create table game_logs_2018_2019 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2024-2025 Season
create table game_logs_2024_2025 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2013-2014 Season
create table game_logs_2013_2014 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2014-2015 Season
create table game_logs_2014_2015 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2016-2017 Season
create table game_logs_2016_2017 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2015-2016 Season
create table game_logs_2015_2016 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

-- 2012-2013 Season
create table game_logs_2012_2013 (
    id integer primary key,
    rk numeric,
    gcar numeric,
    gtm numeric,
    date timestamp,
    team text,
    opp text,
    result text,
    gs text,
    mp text,
    fg text,
    fga text,
    fg_pct text,
    three_p text,
    three_pa text,
    three_p_pct text,
    two_p text,
    two_pa text,
    two_p_pct text,
    efg_pct text,
    ft text,
    fta text,
    ft_pct text,
    orb text,
    drb text,
    trb text,
    ast text,
    stl text,
    blk text,
    tov text,
    pf text,
    pts text,
    gmsc text,
    plus_minus text,
    is_away boolean
);

