-- First, create the per_game stats table
DROP TABLE IF EXISTS per_game_stats;

CREATE TABLE per_game_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season VARCHAR(9) NOT NULL,      -- Format: '2012-13'
  age INTEGER NOT NULL,
  team VARCHAR(5) NOT NULL,        -- Changed from VARCHAR(4) to VARCHAR(5)
  league VARCHAR(5) NOT NULL,      -- Changed from VARCHAR(3) to VARCHAR(5)
  position VARCHAR(2) NOT NULL,
  games INTEGER NOT NULL,
  games_started INTEGER NOT NULL,
  minutes_per_game DECIMAL(4,1) NOT NULL,
  field_goals DECIMAL(3,1) NOT NULL,
  field_goal_attempts DECIMAL(3,1) NOT NULL,
  field_goal_percentage DECIMAL(4,3) NOT NULL,
  three_pointers DECIMAL(3,1) NOT NULL,
  three_point_attempts DECIMAL(3,1) NOT NULL,
  three_point_percentage DECIMAL(4,3) NOT NULL,
  two_pointers DECIMAL(3,1) NOT NULL,
  two_point_attempts DECIMAL(3,1) NOT NULL,
  two_point_percentage DECIMAL(4,3) NOT NULL,
  effective_field_goal_percentage DECIMAL(4,3) NOT NULL,
  free_throws DECIMAL(3,1) NOT NULL,
  free_throw_attempts DECIMAL(3,1) NOT NULL,
  free_throw_percentage DECIMAL(4,3) NOT NULL,
  offensive_rebounds DECIMAL(3,1) NOT NULL,
  defensive_rebounds DECIMAL(3,1) NOT NULL,
  total_rebounds DECIMAL(3,1) NOT NULL,
  assists DECIMAL(3,1) NOT NULL,
  steals DECIMAL(3,1) NOT NULL,
  blocks DECIMAL(3,1) NOT NULL,
  turnovers DECIMAL(3,1) NOT NULL,
  personal_fouls DECIMAL(3,1) NOT NULL,
  points DECIMAL(3,1) NOT NULL,
  awards TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create the advanced stats table
DROP TABLE IF EXISTS advanced_stats;

CREATE TABLE advanced_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season VARCHAR(9) NOT NULL,      -- Format: '2012-13'
  age INTEGER NOT NULL,
  team VARCHAR(5) NOT NULL,        -- Changed from VARCHAR(4) to VARCHAR(5)
  league VARCHAR(5) NOT NULL,      -- Changed from VARCHAR(3) to VARCHAR(5)
  position VARCHAR(2) NOT NULL,
  games INTEGER NOT NULL,
  games_started INTEGER NOT NULL,
  minutes_played INTEGER NOT NULL,
  player_efficiency_rating DECIMAL(4,1) NOT NULL,
  true_shooting_percentage DECIMAL(4,3) NOT NULL,
  three_point_attempt_rate DECIMAL(4,3) NOT NULL,
  free_throw_rate DECIMAL(4,3) NOT NULL,
  offensive_rebound_percentage DECIMAL(4,1) NOT NULL,
  defensive_rebound_percentage DECIMAL(4,1) NOT NULL,
  total_rebound_percentage DECIMAL(4,1) NOT NULL,
  assist_percentage DECIMAL(4,1) NOT NULL,
  steal_percentage DECIMAL(4,1) NOT NULL,
  block_percentage DECIMAL(4,1) NOT NULL,
  turnover_percentage DECIMAL(4,1) NOT NULL,
  usage_percentage DECIMAL(4,1) NOT NULL,
  offensive_win_shares DECIMAL(3,1) NOT NULL,
  defensive_win_shares DECIMAL(3,1) NOT NULL,
  win_shares DECIMAL(3,1) NOT NULL,
  win_shares_per_48 DECIMAL(4,3) NOT NULL,
  offensive_box_plus_minus DECIMAL(3,1) NOT NULL,
  defensive_box_plus_minus DECIMAL(3,1) NOT NULL,
  box_plus_minus DECIMAL(3,1) NOT NULL,
  value_over_replacement DECIMAL(3,1) NOT NULL,
  awards TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create timestamp update function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers
DROP TRIGGER IF EXISTS update_per_game_stats_updated_at ON per_game_stats;
CREATE TRIGGER update_per_game_stats_updated_at
    BEFORE UPDATE ON per_game_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_advanced_stats_updated_at ON advanced_stats;
CREATE TRIGGER update_advanced_stats_updated_at
    BEFORE UPDATE ON advanced_stats
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create indexes
CREATE INDEX per_game_stats_season_idx ON per_game_stats USING btree (season);
CREATE INDEX per_game_stats_team_idx ON per_game_stats USING btree (team);
CREATE INDEX advanced_stats_season_idx ON advanced_stats USING btree (season);
CREATE INDEX advanced_stats_team_idx ON advanced_stats USING btree (team); 